services:
    mysql-db:
        image: mysql:9.6.0
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: azerty
            MYSQL_DATABASE: goatcalendar_db
            MYSQL_USER: goatcalendar_user
            MYSQL_PASSWORD: goatcalendar_passwd
        volumes:
            - mysql-data:/var/lib/mysql
        healthcheck:
            test: ["CMD-SHELL", "mysqladmin ping -h localhost -u root -p$${MYSQL_ROOT_PASSWORD} --silent"]
            interval: 5s
            timeout: 5s
            retries: 10
            start_period: 40s
            
    database-seed:
        image: antonind5/goat-calendar-database_service
        depends_on:
            mysql-db:
                condition: service_healthy
        restart: "no"

    auth-service:
        image: antonind5/goat-calendar-auth_service
        ports:
            - "5001:5001"
        depends_on:
            mysql-db:
                condition: service_healthy
            database-seed:
                condition: service_completed_successfully

    board-service:
        image: antonind5/goat-calendar-board_service
        ports:
            - "5002:5002"
        depends_on:
            mysql-db:
                condition: service_healthy
            database-seed:
                condition: service_completed_successfully

    # front-service:
    #     build:
    #         context: .
    #         dockerfile: production/frontend.Dockerfile
    #     ports:
    #         - "5000:5000"
    #     depends_on:
    #         auth-service:
    #             condition: service_started
    #         board-service:
    #             condition: service_started

volumes:
    mysql-data:
