sonar.organization=goatssoftware
sonar.projectKey=GoatsSoftware_GoatCalendar
sonar.projectName=GoatCalendar
sonar.sourceEncoding=UTF-8

# relative paths to source directories. More details and properties are described
# at https://docs.sonarsource.com/sonarqube-cloud/advanced-setup/analysis-scope/
sonar.sources=.
sonar.test.inclusions=**/*.test.js, **/*_test.py, **/tests/**, **/testing/**
sonar.exclusions=**/node_modules/**, **/dist/**, **/build/**, **/*.test.js, **/.venv/**, **/.github/**, **/.terraform/**, **/*.pdm/**, **/*.idea/**, **/pdm.*/**, **/*.ruff_cache/**, **/*.pdm-build/**, **/__pycache__/**

sonar.python.coverage.reportPaths=tests_coverage.xml
# sonar.javascript.lcov.reportPaths=coverage/lcov.info