sonar.organization=goatssoftware
sonar.projectKey=GoatsSoftware_GoatCalendar
sonar.projectName=GoatCalendar
sonar.sourceEncoding=UTF-8

# relative paths to source directories. More details and properties are described
# at https://docs.sonarsource.com/sonarqube-cloud/advanced-setup/analysis-scope/
sonar.sources=.
sonar.test.inclusions=**/*.test.js, **/*_test.py, **/tests/**, **/testing/**
sonar.exclusions=**/node_modules/**, **/dist/**, **/build/**, **/*.test.js, **/.venv/**, **/.github/**, **/.terraform/**, **/*.pdm/**, **/*.idea/**, **/*.ruff_cache/**, **/*.pdm-build/**, **/__pycache__/**, **/pdm.lock, **/.pdm-python, **/*.db, **/*.sqlite
sonar.scm.exclusions.disabled=true

sonar.python.coverage.reportPaths=coverage-reports/coverage-database_service.xml,coverage-reports/coverage-shared_models.xml,coverage-reports/coverage-auth_service.xml,coverage-reports/coverage-board_service.xml
# sonar.javascript.lcov.reportPaths=coverage/lcov.info
